name:                indexed-transformers
version:             0.2.0.0
github:              "morphismtech/indexed-transformers"
license:             BSD-3-Clause
author:              "Eitan Chatav"
maintainer:          "eitan.chatav@gmail.com"
copyright:           "2026 Eitan Chatav"
category:            Control
synopsis:            Atkey indexed monad transformers

extra-source-files:
- README.md

extra-doc-files:
- CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/morphismtech/indexed-transformers#readme>

dependencies:
- base >= 4.18.1.0 && < 5
- free >= 5.2 && < 6
- kan-extensions >= 5.2.5 && < 6
- mtl >= 2.3.1 && < 3
- transformers >= 0.6.1.0 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DeriveFunctor
- FlexibleInstances
- GADTs
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- QualifiedDo
- QuantifiedConstraints
- RankNTypes
- StandaloneKindSignatures
- TupleSections
- TypeOperators

library:
  source-dirs: src

tests:
  doctests:
    main: Doctests.hs
    source-dirs: test/doctests
    dependencies:
    - doctest >= 0.22.2 && < 1
    - indexed-transformers
  spec:
    main: Spec.hs
    source-dirs: test/spec
    dependencies:
    - hspec >= 2.11.7 && < 3
    - QuickCheck >= 2.14.3 && < 3
    - indexed-transformers
